config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  resources :vehicles
  root 'static_pages#home'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  def index
    @vehicles = Vehicle.all
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      flash[:notice] = "Vehicle has been created."
      redirect_to @vehicle
    else
      # nothing yet
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:name, :make, :model, :year, :engine_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FuelMileage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] %>
  <%= link_to "New Vehicle", new_vehicle_path %>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/vehicles/index.html.erb
<% @vehicles.each do |v| %>
  <ul>
    <li><%= link_to v.name, vehicle_path(v) %></li>
  </ul>
<% end %>

app/views/vehicles/new.html.erb
<%= form_for @vehicle do |f| %>
  <p>
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :make, "Make" %><br />
    <%= f.text_field :make %>
  </p>
  <p>
    <%= f.label :model, "Model" %><br />
    <%= f.text_field :model %>
  </p>
  <p>
    <%= f.label :year, "Year" %><br />
    <%= f.text_field :year %>
  </p>
  <p>
    <%= f.label :engine_type, "Engine Type" %><br />
    <%= f.text_field :engine_type %>
  </p>

  <%= f.submit %>
<% end %>

app/views/vehicles/show.html.erb
<h3>
<%= @vehicle.name %>
</h3>